<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CausaMuerteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $causas = [
            ['ABORTO', 'REPRODUCTOR'],
            ['ABSCESO', 'MULTISISTEMICO'],
            ['ANEMIA', 'CIRCULATORIO'],
            ['ARTICULAR', 'LOCOMOTOR'],
            ['ARTRITIS', 'LOCOMOTOR'],
            ['ASFIXIA MECÁNICA', 'RESPIRATORIO'],
            ['ASFIXIA POR EDEMA DE CUELLO', 'RESPIRATORIO'],
            ['BAJA CONDICION', 'MUSCULOESQUELETICO'],
            ['BAJO DESARROLLO', 'MUSCULOESQUELETICO'],
            ['INCAPACIDAD DEL TREN POSTERIOR', 'LOCOMOTOR'],
            ['CAQUEXIA', 'MUSCULOESQUELETICO'],
            ['CAUDOFAGIA', 'MULTISISTEMICO'],
            ['CIRROSIS HEPATICA', 'DIGESTIVO'],
            ['COLAPSO CARDIO RESPITARIO', 'RESPIRATORIO'],
            ['COMP. CON CIRCOVIRUS', 'TEGUMENTARIO'],
            ['COMP. CON SALMONELLA', 'DIGESTIVO'],
            ['COMP. E COLI', 'DIGESTIVO'],
            ['COMPLEJO RESPIRATORIO', 'RESPIRATORIO'],
            ['CONDICION CORPORAL', 'MUSCULAR'],
            ['CONGESTION', 'RESPIRATORIO'],
            ['DESCARTE POR POSTRACION', 'LOCOMOTOR'],
            ['DESCOMPUESTA', 'DESCONOCIDO'],
            ['EMACIACION', 'MUSCULOESQUELETICO'],
            ['ENDOCARDITIS FIBRINOSA', 'CIRCULATORIO'],
            ['ENDOCARDITIS VALVULAR', 'CIRCULATORIO'],
            ['ENDOCARDITIS VEGETATIVA', 'CIRCULATORIO'],
            ['ENDOMETRITIS', 'REPRODUCTOR'],
            ['ENTERITIS', 'DIGESTIVO'],
            ['ENTERITIS GASEOSA', 'DIGESTIVO'],
            ['ENTERITIS HEMORRAGICA', 'DIGESTIVO'],
            ['ENTEROCOLITIS', 'DIGESTIVO'],
            ['FALLA MULTISISTEMATICA', 'MULTISISTEMICO'],
            ['FALLA RESPIRATORIA', 'RESPIRATORIO'],
            ['FALLO CARDIACO', 'CIRCULATORIO'],
            ['FALLO CARDIO-RESPIRATORIO', 'CIRCULATORIO'],
            ['FALLO RENAL', 'URINARIO'],
            ['FRACTURA DE FEMUR', 'LOCOMOTOR'],
            ['FRACTURA DE MIEMBRO', 'LOCOMOTOR'],
            ['GASTRITIS HEMORRAGICA', 'DIGESTIVO'],
            ['GASTROENTERITIS HEMORRAGICA', 'DIGESTIVO'],
            ['HECES ALQUITRAN', 'DIGESTIVO'],
            ['HEMORRAGIA', 'MULTISISTEMICO'],
            ['HEMORRAGIA ESPLENICA', 'HEMATOPOYETICO'],
            ['HEMORRAGIA HEPATICA', 'DIGESTIVO'],
            ['HEMORRAGIA INTERNA', 'MULTISISTEMICO'],
            ['HEMORRAGIA RUPTURA HEPATICA', 'DIGESTIVO'],
            ['HEMORRAGIA RUPTURA UTERINA', 'REPRODUCTOR'],
            ['HEMORRAGIA VULVAR', 'REPRODUCTOR'],
            ['HEPATOMEGALIA', 'DIGESTIVO'],
            ['HERNIA UMBILICAL', 'DIGESTIVO'],
            ['HERNIA ESCROTAL', 'MUSCULOESQUELETICO'],
            ['HIDRONEFROSIS', 'URINARIO'],
            ['INANICIÓN', 'DIGESTIVO'],
            ['INFARTO', 'CIRCULATORIO'],
            ['INFARTO AL MIOCARDIO', 'CIRCULATORIO'],
            ['INFLAMACION ARTICULAR', 'LOCOMOTOR'],
            ['INSUFICIENCIA CARDIO-RESPIRATORIO', 'CIRCULATORIO'],
            ['INSUFICIENCIA RENAL', 'URINARIO'],
            ['LESIONES COMP. CON CIRCOVIRUS', 'MULTISISTEMICO'],
            ['LESIONES COMP. CON E COLI', 'DIGESTIVO'],
            ['LESIONES COMP. CON POLISEROSITIS', 'RESPIRATORIO'],
            ['LESIONES COMP. CON SALMONELLA', 'DIGESTIVO'],
            ['LUXACION DE LA CABEZA DEL FEMUR', 'LOCOMOTOR'],
            ['MALA CONDICION', 'MUSCULAR'],
            ['MASTITIS', 'REPRODUCTOR'],
            ['METRITIS', 'REPRODUCTOR'],
            ['METRITIS CRONICA', 'REPRODUCTOR'],
            ['MIOCARDITIS', 'CIRCULATORIO'],
            ['MUERTE SÚBITA', 'DESCONOCIDO'],
            ['MUERTO EN TRASLADO', 'DESCONOCIDO'],
            ['NEFRITIS', 'URINARIO'],
            ['NEFROSIS', 'URINARIO'],
            ['NEOPLASIA', 'MULTISISTEMICO'],
            ['NEOPLASIA ESPLENICA', 'DIGESTIVO'],
            ['NEUMONÍA', 'RESPIRATORIO'],
            ['NEUMONIA ABSCEDATIVA', 'RESPIRATORIO'],
            ['NEUMONIA INTERSTICIAL', 'RESPIRATORIO'],
            ['PANCREATITIS', 'DIGESTIVO'],
            ['PARO CARDIACO', 'CIRCULATORIO'],
            ['PERICARDITIS', 'CIRCULATORIO'],
            ['PERICARDITIS FIBRINOSA', 'CIRCULATORIO'],
            ['PERITONITIS', 'DIGESTIVO'],
            ['PIELONEFRITIS', 'URINARIO'],
            ['PLEURONEUMONIA', 'RESPIRATORIO'],
            ['PODODERMATITIS', 'LOCOMOTOR'],
            ['POLISEROSITIS', 'DIGESTIVO'],
            ['POSIBLE FRACTURA', 'LOCOMOTOR'],
            ['POSTRADA', 'LOCOMOTOR'],
            ['POSTRADA(O)', 'LOCOMOTOR'],
            ['POSTRADA(O) PODAL', 'LOCOMOTOR'],
            ['PROBLEMA NERVIOSO', 'NERVIOSO'],
            ['PROBLEMAS DE LOCOMOCION', 'LOCOMOTOR'],
            ['PROBLEMAS PODALES', 'LOCOMOTOR'],
            ['PROLAPSO', 'REPRODUCTOR'],
            ['PROLAPSO RECTAL', 'URINARIO'],
            ['PROLAPSO UTERINO', 'REPRODUCTOR'],
            ['PROLAPSO VESICAL', 'REPRODUCTOR'],
            ['RETENCIÓN', 'REPRODUCTOR'],
            ['RUPTURA DE VEJIGA', 'URINARIO'],
            ['RUPTURA ESPLENICA', 'HEMATOPOYETICO'],
            ['RUPTURA GASTRICA', 'DIGESTIVO'],
            ['RUPTURA HEPATICA', 'DIGESTIVO'],
            ['S.P.A', 'REPRODUCTOR'],
            ['SALMONELLA', 'DIGESTIVO'],
            ['SEPTICEMIA', 'HEMATOPOYETICO'],
            ['SINTOMAS NERVIOSO', 'NERVIOSO'],
            ['TORSION GASTRICA', 'DIGESTIVO'],
            ['TORSION INTESTINAL', 'DIGESTIVO'],
            ['UBRE DESPREDIDA', 'DIGESTIVO'],
            ['ULCERA GASTRICA', 'DIGESTIVO'],
            ['ULCERA HEMORRAGICA', 'DIGESTIVO'],
            ['NEUMONIA CATARRAL', 'RESPIRATORIO'],
            ['ESPLENOMEGALIA', 'DIGESTIVO'],
        ];

        $data = [];
        foreach ($causas as $causa) {
            $data[] = [
                'causa' => $causa[0],
                'sistema' => $causa[1],
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('causas_muerte')->insert($data);
    }
}
